### ISSUE TITLE
3차 주제 회의

### ISSUE THREAD

**Issue by Dukapuri** [TaeHoonHer/Capstone_Design#1]
아이디어에 대한 주제를 정하기 위해 2023년 3월 10일 구글 Meet으로 회의 진행

**Comment by Dukapuri** [comment]
For # 이라는 사진을 좋은 구도로 찍어주는 어플리케이션을 만들기로 주제를 정함
- 안드로이드 : 주 기능으로느 사진을 촬영하며 다양한 보조 기능을 넣음
- 프론트엔드 : 사용자에게 찍은 사진들을 클라우드 형식으로 쉽게 보여주면서 서로 공유할 수 있는 커뮤니티 생성
- 백엔드 : 모든 서비스가 잘 이루어 질 수 있도록 중간 통신 역할을 하며 보안과 트래픽 처리를 함
- 인공지능 : 사람의 비율을 더 좋게 찍을 수 있도록 실시간으로 보여주고 AI를 사용한 다양한 기능을 제공한다.

**Comment by j2an777** [comment]
프론트 : Icon, splash 페이지 제작 완료
